language: node_js

node_js:
  - 12

deploy:
  provider: lambda
  function_name: "c2w-lambda-users-$TRAVIS_BRANCH"
  region: "eu-west-1"
  role: "arn:aws:iam::881121095103:role/travis"
  runtime: "nodejs12.x"
  module_name: "bundle/index"
  handler_name: "handler"
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  environment_variables:
    - STRAVA_ACCESS_TOKEN=$STRAVA_ACCESS_TOKEN
    - STRAVA_CLIENT_ID=$STRAVA_CLIENT_ID
    - STRAVA_CLIENT_SECRET=$STRAVA_CLIENT_SECRET
    - MONGODB_URL=$MONGODB_URL
    - LOG_LEVEL=debug

script:
  - yarn lint
  - yarn coverage
  - yarn codecov
  - yarn build
